project: default
metadata:
  name: nextapp
  namespace: nextapp
source:
  repoURL: 'https://github.com/JBongars/helm-next-deployment-template.git'
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: nextapp
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - Replace=true
